searchPath with expand
Shougo/ddu-ui-filer pull request #19
Opened 2023-01-10 14:57 UTC by hori-ryota

2023-01-10 15:18 UTC, hori-ryota commented on denops/@ddu-uis/filer.ts
> +    if (this.toSearchPath) {
search処理なので

https://github.com/Shougo/ddu-ui-filer/commit/7f9173f38bfdecd37b289bd7530b7a07dc5a8f42#diff-ec46f25956f2efae1084299788196f796090fdaf98c35521267a39bd49fcffe0L362

で消えたsearch処理のところに入れてみました

2023-01-10 23:58 UTC, Shougo requested changes
diff が大きいので、説明もなしにマージはできません。
なにがやりたいのかをもっと具体的に説明してください。

2023-01-11 00:54 UTC, hori-ryota commented
### 実現したいこと

`ddu-ui-filer-param-search` 時代と同じく、search処理実行時にexpandさせたい

### 詳細

https://github.com/Shougo/ddu-ui-filer/issues/17#issuecomment-1377321632

の件で、

https://github.com/Shougo/ddu-ui-filer/issues/17#issuecomment-1377050230

によりsearch時にexpandしなくなったかと思います。

expandさせるため、searchPathメソッドでitemを探索し、expandされていない親（treePathがsearchのprefixである）を見つけたら `ddu#redraw_tree` にてexpandするようにしました。

expand後に再度 searchPathメソッドでitemにカーソルを合わせたいため、 `this.toSearchPath` にsearch対象を格納し、redraw時に `this.toSeachPath` が入っていれば searchPathを実行するようにしました。
（todo的に変数に格納しておき、処理＆clearする仕組みはddu本体の `searchPath` と同じ仕組み）

2023-01-11 01:53 UTC, Shougo commented
なるほど。やりたいことは理解しましたが、この処理を UI 側で行うのは非常に筋が悪いといえます。
ddu.vim の中で処理をするべきでしょう。

2023-01-11 03:22 UTC, hori-ryota commented
> この処理

expand自体ではなく `this.toSeachPath` のところですよね、expandにsearchを指定していたらそもそもカーソルが合うようddu.vim側でアレコレするのが自然なのはたしかにそうなので、やってみます。

2023-01-11 03:28 UTC, hori-ryota commented
> expandにsearchを指定していたらそもそもカーソルが合うようddu.vim側でアレコレする

これは既になっていましたね。 `this.toSeachPath` 部を削除してみます。

2023-01-11 03:45 UTC, hori-ryota commented
`this.toSearchPath` 周りを掃除しました。

expand判定をddu.vim側でやるとすると [Ddu.uiRedraw](https://github.com/Shougo/ddu.vim/blob/54b5a571e735e56e816cbb7755ab8eeab65905a0/denops/ddu/ddu.ts#L436-L504) らへんでしょうか。

実装できそうに見えますが、pathからitemの解決をuiRedrawで行うと `ui.searchPath` は不要で `ui.searchItem` があれば足りそうに見えました。設計思想を把握してから触ったほうが良さそうなのでいったん意見いただけますと幸いです。

2023-01-11 03:53 UTC, hori-ryota commented
`ddu.vim` 側だと [ui.refreshItems](https://github.com/Shougo/ddu.vim/blob/54b5a571e735e56e816cbb7755ab8eeab65905a0/denops/ddu/ddu.ts#L473-L481) 後のuiが保持するitemsがわからないのでexpand判定ができなさそうに見えました。

一方で `ui.refreshItems` の戻り値にuiが保持するitemsを返すのは違和感なさそうに見えるので、もしインターフェースを変更してよければ ddu.vim 側で実装できるかもです。

（そもそもui側が保持しているitemsではなく `uiRedraw` に渡ってくるitemsに対してexpand判定をすればいいという話でしたら素直にできそうです）

2023-01-11 04:10 UTC, Shougo commented
> 実装できそうに見えますが、pathからitemの解決をuiRedrawで行うと ui.searchPath は不要で ui.searchItem があれば足りそうに見えました。設計思想を把握してから触ったほうが良さそうなのでいったん意見いただけますと幸いです。

それは確かにそうですね

2023-01-11 04:52 UTC, Shougo commented
ddu.vim 本体のほうで対応しました。確認しください。

2023-01-11 04:52 UTC, closed without merging

2023-01-12 08:29 UTC, hori-ryota commented
なんか `ddu-option-searchPath` の更新時に変な動きをする（無限ループっぽい挙動）のでデバッグしてみます

2023-01-12 09:17 UTC, hori-ryota commented
とりあえず見つけた挙動ですが、uiRedrawに渡ってくるitemsの `__expanded` がtrueにならないようです。

https://github.com/Shougo/ddu.vim/blob/e99c66b1f518583ae0fdce595428bf6f2c2ff96f/denops/ddu/ddu.ts#L501

下記vimrcで

1. `<space>e` でfilerを開く
2. `<space>r` でsearchPathを書き換える

で2ではtreeが展開されずカーソルが上下に1, 2で展開される両ディレクトリ間を往復します。

```vim
set runtimepath+=path/to/vim-denops/denops.vim
set runtimepath+=path/to/Shougo/ddu.vim
set runtimepath+=path/to/Shougo/ddu-ui-filer
set runtimepath+=path/to/Shougo/ddu-column-filename
set runtimepath+=path/to/Shougo/ddu-source-file
set runtimepath+=path/to/Shougo/ddu-kind-file

nnoremap <silent> <space>e <Cmd>call ddu#start({
      \   'name': 'ddutest',
      \   'ui': 'filer',
      \   'sync': v:true,
      \   'sources': [{
      \     'name': 'file',
      \     'options': {
      \       'path': getcwd(),
      \       'columns': ['filename'],
      \     },
      \   }],
      \   'searchPath':  'path/to/Shougo/ddu.vim/denops/ddu/deps.ts',
      \ })<CR>

nnoremap <silent> <space>r <Cmd>call ddu#redraw('ddutest', {'updateOptions': {
      \   'searchPath': 'path/to/Shougo/ddu.vim/denops/ddu/base/source.ts',
      \ }})<CR>
```

2023-01-12 09:48 UTC, hori-ryota commented
treePathがprefixになっているか否かで判定しようかと思いましたが、

- dirA
- dirAB
- dirAB/fileA

みたいな構成の場合、dirAもprefixとして一致するので展開されちゃいますね…

2023-01-12 10:50 UTC, Shougo commented
調査していますが、この問題はかなり根が深いことが分かりました

2023-01-12 10:52 UTC, Shougo commented
とりあえず手元でパスの問題と無限ループだけ直したので、あとは任せます。
Please update `ddu.vim` to the latest.

2023-01-12 11:50 UTC, hori-ryota commented
機能は多分複雑ではなくて、itemのデータが不整合を起こす（ `__expanded` が維持されない）のが問題かと思っています。

もしddu.vim側で `__expand` の情報が正しく維持されないのであれば `__expanded` の管理はddu.vimの責務ではなくなるのでui側で管理になるかと思います。

`this.expandedPaths` を用意していただいたので、そもそもrefresh時に `__expanded` を正しくする処理を入れられるか試してみます。

2023-01-13 05:02 UTC, hori-ryota commented
`__expand` が正しくなるようにしました

> [fix mismatch of \`\_\_expanded\` flag by hori\-ryota · Pull Request \#35 · Shougo/ddu\.vim](https://github.com/Shougo/ddu.vim/pull/35)

上記が入れられればddu.vim側でexpandの状態管理が満たせるようになるので、ddu-ui-filerのexpand管理を掃除するプルリクも用意しました

> [remove expanded memo by hori\-ryota · Pull Request \#20 · Shougo/ddu\-ui\-filer](https://github.com/Shougo/ddu-ui-filer/pull/20)